### ISSUE TITLE
Mobile menu is the wrong color

### ISSUE THREAD

**Issue by gazayas** [bullet-train-co/bullet_train-themes-light#52]
Was looking into this TODO:
```CSS
.bg-primary-900 {
  /* TODO We can't really do this. We need to just append a transparency class to these elements. */
  background-color: rgba(0, 0, 0, 0.15);
}
```

Found out the mobile menu currently looks like this:
![Screenshot from 2022-09-10 10-12-54](https://user-images.githubusercontent.com/10546292/189463045-e706f3cc-eb19-43b8-a7cd-f2769be5aa9c.png)
